source "https://rubygems.org/"
ruby "2.0.0"

gem "sinatra"
gem "omniauth"
gem "omniauth-github"
gem "omniauth-facebook"
gem "omniauth-twitter"
gem "omniauth-google-oauth2"

gem "foreman"
gem "thin"

gem "minitest"
gem "rake"
